### ISSUE TITLE
Kimchi will not run on Ubuntu 16.04 (or any Libvirt version <2.0.0)

### ISSUE THREAD

**Issue by overcookedTOFU** [kimchi-project/kimchi#1164]
As of commit 0787baa , wok fails to load the kimchi plugin with the following error: 

> Failed to import plugin plugins.kimchi.Kimchi, error: 'module' object has no attribute 'VIR_STORAGE_POOL_EVENT_DEFINED'

The most recent version of libvirt available on Ubuntu 16.04 is libvirt 1.3.1, which does not support the storage pool lifecycle event monitoring introduced in Kimchi commit 0b857ab.

**Comment by majoess** [comment]
For me its working on Ubuntu Server 16.04(.03) LTS 64bit, GA350.

**Comment by VamPikmin** [comment]
Did you have to do anything specific to get it working?
I keep getting
Failed to import plugin plugins.kimchi.Kimchi, error: 'module' object has no attribute 'VIR_STORAGE_POOL_EVENT_DEFINED'

libvirt version: 1.3.1

**Comment by majoess** [comment]
no, did nothing.

**Comment by majoess** [comment]
but running with some special grub parameter due ryzen

**Comment by majoess** [comment]
@cyrillegin I don't know anymore. I wiped my home server.
